### ISSUE TITLE
Profile information is not saved

### ISSUE THREAD

**Issue by delebash** [UseLessUK/KICS-EliteVA#1]
Thanks for this.  It asks me for profile information every time I start VA.  Besides the user ids for inara and edsm the info I enter into the prompt boxes is not saved.

Here is the data file

>ed.ds.trigger:1
>ed.ds.firegroup:-1
>ed.hb.trigger:1
>ed.hb.firegroup:-1
>ed.srv.dls.trigger:1
>ed.srv.dls.firegroup:-1
>ed.srv.cs.trigger:1
>ed.srv.cs.firegroup:-1
>ed.ship.dls.trigger:1
>ed.ship.dls.firegroup:-1
>ed.ship.cs.trigger:1
>ed.ship.cs.firegroup:-1
>ed.inara.id:1234
>ed.edsm.id:1234

**Comment by UseLessUK** [comment]
Found a bug.

Download the updated vap file which should fix your issue.

**Comment by UseLessUK** [comment]
Made some other changes to the vap file so if you've downloaded it within the last 6 or so hours then you should download it again as it's changed.

**Comment by UseLessUK** [comment]
Also there should not be any -1 values in the data ... a -1 value means an option has not been selected which is why you'll be asked for it upon next profile load

**Comment by delebash** [comment]
Thanks, I will give the new one a try.  I am selecting options for firing groups and clicking ok, it just is not saving it to the file correctly.  TY

**Comment by delebash** [comment]
all fixed ty
